---
- set_fact:
    disks_layout:
    - size_gb: 120
      type: thin
      datastore: "{{ datastore | default(vcenter_provision_datastore) }}"
- set_fact:
    disks_layout: "{{ disks_layout + additional_storage }}"
  when: additional_storage is defined
- debug:
    var: disks_layout
- name:  Clone a virtual machine from Linux template and customize
  vmware_guest:
    hostname: "{{ vcenter_provision_hostname }}"
    username: "{{ vcenter_provision_username }}"
    password: "{{ vcenter_provision_password }}"
    validate_certs: no
    datacenter: "{{ vcenter_provision_datacenter }}"
    state: present
    folder: "{{ vcenter_provision_folder }}"
    template: "{{ vcenter_provision_default_rhcos_template }}"
    name: "{{ inventory_hostname_short }}"
    cluster: "{{ vcenter_provision_cluster }}"
    is_template: no
    hardware:
      hotadd_cpu: yes
      hotremove_cpu: yes
      hotadd_memory: yes
      num_cpus: "{{ cpu }}"
      memory_mb: "{{ ram|int*1024 }}"
    disk: "{{ disks_layout }}"
    networks:
      - name: "{{ vcenter_provision_network_name }}"
    customvalues:
      - key: "guestinfo.ignition.config.data"
        value: "{{ ignition_data }}"
      - key: "guestinfo.ignition.config.data.encoding"
        value: "base64"
      - key: "disk.EnableUUID"
        value: "TRUE"
    wait_for_ip_address: False
  delegate_to: localhost
  register: created_vm
- name: set MAC 
  vmware_guest_network:
    hostname: "{{ vcenter_provision_hostname }}"
    username: "{{ vcenter_provision_username }}"
    password: "{{ vcenter_provision_password }}"
    validate_certs: no
    datacenter: "{{ vcenter_provision_datacenter }}"
    name: "{{ inventory_hostname_short }}"
    gather_network_info: false
    networks:
      - mac: "{{ created_vm.instance.hw_eth0.macaddress }}"
        state: present
        manual_mac: "{{ mac }}"
        connected: true
  delegate_to: localhost
  register: network_info
  when: mac is defined
  tags: set_mac

- name: Add virtual machine custom attributes
  vmware_guest_custom_attributes:
    hostname: "{{ vcenter_provision_hostname }}"
    username: "{{ vcenter_provision_username }}"
    password: "{{ vcenter_provision_password }}"
    validate_certs: no
    datacenter: "{{ vcenter_provision_datacenter }}"
    name: "{{ inventory_hostname_short }}"
    state: present
    attributes: "{{ (vcenter_provision_custom_attributes | from_yaml )| union( (vcenter_provision_custom_attributes_additional | from_yaml ) | default([]) ) }}"
  delegate_to: localhost
  tags: tags

- name: Set the state of a virtual machine to poweron
  vmware_guest_powerstate:
    hostname: "{{ vcenter_provision_hostname }}"
    username: "{{ vcenter_provision_username }}"
    password: "{{ vcenter_provision_password }}"
    validate_certs: no
    folder: "{{ vcenter_provision_folder }}"
    name: "{{ inventory_hostname_short }}"
    state: powered-on
  delegate_to: localhost
  register: deploy
  tags: start_vm